using System;

namespace pascalCsharp.frontend
{
    using pascalCsharp.intermediate.ICode;
    using pascalCsharp.intermediate.SymTab;


    public abstract class Parser
    {
        protected static SymTab symTab = null;  // generated symbol table
        protected Scanner scanner;              // scanner used with this parser
        protected ICode iCode;                  // intermediate code generated by this parser

        protected Parser(Scanner scanner)
        {
            this.scanner = scanner;
            this.iCode = null;
        }

        public abstract void parse();
    }
}
